---
title: See like a bat
hero_image: images/banner.png
description: In this resource you will make an echolocation device using your Raspberry
Pi
original_url: https://raspberrypi.org/learning/see-like-a-bat
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-3, manufacture-0, community-0
interests: animals
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Adding flying leads to the vibration motor
- title: Testing the vibration motor
- title: How an ultrasonic distance sensor (UDS) works
- title: Potential dividers
- title: Wiring the UDS
- title: Testing the UDS
- title: Calculating the distance
- title: Adding the Vibration motor
- title: Debugging your script
- title: Making it durable
- title: Making it wearable
- title: What next?